[package]
name = "chiptrack"
version = "0.2.0"
authors = ["Jocelyn Turcotte <turcotte.j@gmail.com>"]
edition = "2018"

## wasm build stuff
## Uncomment and build with: wasm-pack build --release --target web
# resolver = "2"
# [lib]
# crate-type = ["cdylib"]
# path = "src/main.rs"
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2" }
# web-sys = { version = "0.3", features=["console", "Location", "UrlSearchParams"] }
# console_error_panic_hook = "0.1.5"
# [patch.crates-io]
# blip_buf = { path = "../blip_buf-rs"}


[dependencies]
once_cell = "1"
cpal = { version = "0.13", features = ["wasm-bindgen"] }
tiny-skia = "0.6"
rhai = { version = "1", features = ["only_i32"] }
serde_json = "1"
notify = "4"
midir = "0.8"
midly = "0.5"
url = "2"
ehttp = "0.2"
bit-set = "0.5"
pulldown-cmark = "0.9"
regex = "1"
native-dialog = "0.6"

[dependencies.slint]
version = "0.3"
default-features = false
# Re-enable everything except "backend-qt"
features = ["std", "backend-winit", "renderer-winit-femtovg", "compat-0-3-0"]

[build-dependencies.slint-build]
version = "0.3"

[dependencies.rboy]
git = "https://github.com/jturcotte/rboy.git"
rev = "836b4e7a58288a29c13bf7f8b967358c7331ee41"
# Use as a lib, features are used by its bin's main.rs only.
default-features = false
