[package]
name = "chiptrack"
version = "0.2.0"
authors = ["Jocelyn Turcotte <turcotte.j@gmail.com>"]
edition = "2018"

[features]
std = ["slint/std", "cpal", "rboy", "once_cell", "tiny-skia", "serde_json", "notify", "midir", "midly", "url", "ehttp", "pulldown-cmark", "regex", "native-dialog"]

default = ["std"]

## wasm build stuff
## Uncomment and build with: wasm-pack build --release --target web
# resolver = "2"
# [lib]
# crate-type = ["cdylib"]
# path = "src/main.rs"
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = { version = "0.2" }
# web-sys = { version = "0.3", features=["console", "Location", "UrlSearchParams"] }
# console_error_panic_hook = "0.1.5"
# [patch.crates-io]
# blip_buf = { path = "../blip_buf-rs"}


[dependencies]
cpal = { version = "0.13", features = ["wasm-bindgen"], optional = true }
once_cell = { version = "1", optional = true }
tiny-skia = { version = "0.6", optional = true }
serde_json = { version = "1", optional = true }
notify = { version = "4", optional = true }
midir = { version = "0.8", optional = true }
midly = { version = "0.5", optional = true }
url = { version = "2", optional = true }
ehttp = { version = "0.2", optional = true }
pulldown-cmark = { version = "0.9", optional = true }
regex = { version = "1", optional = true }
native-dialog = { version = "0.6", optional = true }

[dependencies.slint]
version = "0.3"
default-features = false
# Re-enable everything except "backend-qt"
features = ["std", "backend-winit", "renderer-winit-femtovg", "compat-0-3-0"]

[build-dependencies.slint-build]
version = "0.3"

[dependencies.rboy]
git = "https://github.com/jturcotte/rboy.git"
rev = "836b4e7a58288a29c13bf7f8b967358c7331ee41"
# Use as a lib, features are used by its bin's main.rs only.
default-features = false
optional = true

[dependencies.wamr-sys]
git = "https://github.com/jturcotte/wamr-sys.git"
rev = "93546401ecdfb7beb6856d42b6cb7bca3941fa33"
default-features = false
