import {
    GlobalEngine
} from "globals.slint";

export enum FocusedPanel { patterns, steps, instruments }

// State shared by the desktop and gba UIs is put here in a
// global to avoid having to duplicate them in the separate root components.
export global GlobalUI {
    // param0, param1, press, release
    in-out property<int> selected_column: 2;
    in-out property<bool> x_pressed: false;
    in-out property<bool> z_pressed: false;

    public function cycle_step_colum(forward: bool) {
        if (forward && GlobalUI.selected_column < 3) {
            GlobalUI.selected_column += 1;
        } else if (!forward && GlobalUI.selected_column > 0){
            GlobalUI.selected_column -= 1;
        }
    }
}


export component PatternsFocusScope inherits FocusScope {
    callback root_key_pressed(KeyEvent) -> EventResult;
    callback root_key_released(KeyEvent) -> EventResult;

    key_pressed(e) => {
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = true;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = true;
        }

        if (GlobalUI.z_pressed && e.text == "x") { if (!e.repeat) { GlobalEngine.remove_last_song_pattern(); } }
        else if (e.text == "x") { if (!e.repeat) { GlobalEngine.cycle_song_pattern_start(); } }
        else if (GlobalUI.x_pressed && e.text == Key.LeftArrow) { GlobalEngine.cycle_song_pattern(false); }
        else if (GlobalUI.x_pressed && e.text == Key.RightArrow) { GlobalEngine.cycle_song_pattern(true); }
        else {
            return root_key_pressed(e);
        }
        return accept;
    }
    key_released(e) => {
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = false;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = false;
        }

        return root.root_key_released(e);
    }

}

export component StepsFocusScope inherits FocusScope {
    callback root_key_pressed(KeyEvent) -> EventResult;
    callback root_key_released(KeyEvent) -> EventResult;

    key_pressed(e) => {
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = true;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = true;
        }

        if (GlobalUI.selected_column < 2 /*params*/ && GlobalUI.z_pressed && e.text == "x") { if (!e.repeat) { GlobalEngine.cut_selected_step_param(GlobalUI.selected_column); } }
        else if (GlobalUI.z_pressed && e.text == "x") { if (!e.repeat) { GlobalEngine.cut_selected_step_note(); } }
        else if (GlobalUI.selected_column < 2 /*params*/ && e.text == "x") { if (!e.repeat) { GlobalEngine.cycle_step_param_start(GlobalUI.selected_column); } }
        // else if (GlobalUI.selected_column < 2 /*params*/ && GlobalUI.x_pressed && e.text == Key.UpArrow) { GlobalEngine.cycle_step_param(1, true); }
        // else if (GlobalUI.selected_column < 2 /*params*/ && GlobalUI.x_pressed && e.text == Key.DownArrow) { GlobalEngine.cycle_step_param(1, false); }
        else if (GlobalUI.selected_column < 2 /*params*/ && GlobalUI.x_pressed && e.text == Key.LeftArrow) { GlobalEngine.cycle_step_param(GlobalUI.selected_column, false); }
        else if (GlobalUI.selected_column < 2 /*params*/ && GlobalUI.x_pressed && e.text == Key.RightArrow) { GlobalEngine.cycle_step_param(GlobalUI.selected_column, true); }
        else if (GlobalUI.selected_column == 2 /*press*/ && e.text == "x") { if (!e.repeat) { GlobalEngine.cycle_note_start(); } }
        else if (GlobalUI.selected_column == 2 /*press*/ && GlobalUI.x_pressed && e.text == Key.UpArrow) { GlobalEngine.cycle_note(true, true); }
        else if (GlobalUI.selected_column == 2 /*press*/ && GlobalUI.x_pressed && e.text == Key.DownArrow) { GlobalEngine.cycle_note(false, true); }
        else if (GlobalUI.selected_column == 2 /*press*/ && GlobalUI.x_pressed && e.text == Key.LeftArrow) { GlobalEngine.cycle_note(false, false); }
        else if (GlobalUI.selected_column == 2 /*press*/ && GlobalUI.x_pressed && e.text == Key.RightArrow) { GlobalEngine.cycle_note(true, false); }
        else if (GlobalUI.selected_column == 3 /*release*/ && e.text == "x") { if (!e.repeat) { GlobalEngine.toggle_selected_step_release(); } }
        else if (!GlobalUI.z_pressed && !e.modifiers.shift && e.text == Key.LeftArrow) { GlobalUI.cycle_step_colum(false); }
        else if (!GlobalUI.z_pressed && !e.modifiers.shift && e.text == Key.RightArrow) { GlobalUI.cycle_step_colum(true); }
        else if (!GlobalUI.z_pressed && e.text == Key.UpArrow) { GlobalEngine.select_next_step(false); }
        else if (!GlobalUI.z_pressed && e.text == Key.DownArrow) { GlobalEngine.select_next_step(true); }
        else {
            return root_key_pressed(e);
        }
        return accept;
    }
    key_released(e) => { 
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = false;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = false;
        }

        if (GlobalUI.selected_column < 2 /*params*/ && e.text == "x") { GlobalEngine.cycle_step_param_end(GlobalUI.selected_column); }
        else if (GlobalUI.selected_column == 2 /*press*/ && e.text == "x") { GlobalEngine.cycle_note_end(); }
        else {
            return root_key_released(e);
        }
        return accept;
    }
}

export component InstrumentsFocusScope inherits FocusScope {
    callback root_key_pressed(KeyEvent) -> EventResult;
    callback root_key_released(KeyEvent) -> EventResult;

    key_pressed(e) => {
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = true;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = true;
        }

        if (e.text == "x") { if (!e.repeat) { GlobalEngine.cycle_instrument_param_start(); } }
        else if (GlobalUI.x_pressed && e.text == Key.UpArrow) { GlobalEngine.cycle_instrument_param(1, true); }
        else if (GlobalUI.x_pressed && e.text == Key.DownArrow) { GlobalEngine.cycle_instrument_param(1, false); }
        else if (GlobalUI.x_pressed && e.text == Key.LeftArrow) { GlobalEngine.cycle_instrument_param(0, false); }
        else if (GlobalUI.x_pressed && e.text == Key.RightArrow) { GlobalEngine.cycle_instrument_param(0, true); }
        else if (e.text == Key.UpArrow) { GlobalEngine.cycle_instrument(0, -1); }
        else if (e.text == Key.DownArrow) { GlobalEngine.cycle_instrument(0, 1); }
        else if (!e.modifiers.shift && e.text == Key.LeftArrow) { GlobalEngine.cycle_instrument(-1, 0); }
        else if (!e.modifiers.shift && e.text == Key.RightArrow) { GlobalEngine.cycle_instrument(1, 0); }
        else {
            return root_key_pressed(e);
        }
        return accept;
    }
    key_released(e) => { 
        if (e.text == "x" && !e.repeat) {
            GlobalUI.x_pressed = false;
        } else if (e.text == "z" && !e.repeat) {
            GlobalUI.z_pressed = false;
        }

        if (e.text == "x") { GlobalEngine.cycle_instrument_param_end(); }
        else {
            return root_key_released(e);
        }
        return accept;
    }
}