// Copyright © 2021 Jocelyn Turcotte <turcotte.j@gmail.com>
// SPDX-License-Identifier: MIT

struct SongPatternData := {
    number: int,
    active: bool,
}
struct PatternData := {
    empty: bool,
    active: bool,
}
struct StepData := {
    press: bool,
    release: bool,
    active: bool,
    note_name: string,
}
struct InstrumentData := {
    id: string,
    selected: bool,
    active: bool,
    muted: bool,
}
struct NoteData := {
    note_number: int,
    key_pos: int,
    is_black: bool,
    active: bool,
}
struct ChannelTraceNote := {
    tick_number: int,
    octave: int,
    key_pos: int,
    is_black: bool,
    volume: float,
    color: color,
}
struct ChannelActiveNote := {
    trace: ChannelTraceNote,
    note_name: string,
}

export {
    SongPatternData,
    PatternData,
    StepData,
    InstrumentData,
    NoteData,
    ChannelTraceNote,
    ChannelActiveNote
}
