// Copyright © 2022 Jocelyn Turcotte <turcotte.j@gmail.com>
// SPDX-License-Identifier: MIT

import { Button, ComboBox, GridBox, SpinBox, VerticalBox, HorizontalBox } from "std-widgets.slint";

import { GlobalSettings } from "globals.slint";

component OverlayDialog inherits Rectangle {
    callback accepted();
    background: #ffffffC0;
    width: 100%;
    height: 100%;
    // Eat events beside the dialog
    TouchArea {
        width: 100%;
        height: 100%;
    }
    Rectangle {
        background: white;
        border-color: grey;
        border_width: 2px;
        border_radius: 10px;
        width: 80%;
        height: 80%;
        x: self.width / 0.8 * 0.1;
        y: self.height / 0.8 * 0.1;
    }
    HorizontalLayout {
        padding_left: self.width / 0.8 * 0.1;
        padding_top: self.height / 0.8 * 0.1;
        padding_right: self.padding_left;
        padding_bottom: self.padding_top;
        VerticalBox {
            Rectangle {
                @children
            }
            Rectangle {
                vertical-stretch: 1;
            }
            HorizontalBox {
                alignment: end;    
                Button { 
                    text: "OK";
                    clicked => { root.accepted(); }
                }
            }
        }        
    }
}

export component SettingsDialog inherits OverlayDialog {
    callback closed();
    accepted => {
        GlobalSettings.settings.sync_enabled = sync_control.current_value != "Off";
        GlobalSettings.settings_changed(GlobalSettings.settings);
        GlobalSettings.song_settings.frames_per_step = frames_per_step_control.value;
        GlobalSettings.song_settings_changed(GlobalSettings.song_settings);
        closed();
    }
    GridBox {
        spacing: 24px;
        Row {
            Text {
                text: "Settings";
                font_size: 24px;
            }
        }
        Row {
            Text {
                vertical_alignment: center;
                text: "Sync Mode";
            }
            sync_control := ComboBox {
                model: ["Off", "PO SY1 (master, left channel is 2 PPQN)"];
                current_value: GlobalSettings.settings.sync_enabled ? "PO SY1 (master, left channel is 2 PPQN)" : "Off";
            }
        }
        Row {
            Text {
                text: "Song Settings";
                font_size: 24px;
            }
        }
        Row {
            Text {
                vertical_alignment: center;
                text: "Frames per step";
            }
            HorizontalBox {
                padding: 0px;
                frames_per_step_control := SpinBox {
                    value: GlobalSettings.song_settings.frames_per_step;
                    minimum: 1;
                    maximum: 16;
                }
                Text {
                    preferred-width: 80px;
                    vertical_alignment: center;
                    horizontal_alignment: right;
                    property<float> bpm: 60 /* s */ * 60 /* fps */ / 4 /* steps per beat */ / frames_per_step_control.value;
                    text: "(~" + round(bpm) + " BPM)";
                }
            }
        }
    }
}
