// Copyright © 2021 Jocelyn Turcotte <turcotte.j@gmail.com>
// SPDX-License-Identifier: MIT

import {
    Button,
    HorizontalBox,
    VerticalBox
} from "std-widgets.slint";

import {
    SongPatternData,
    PatternData,
    GlobalEngine
} from "globals.slint";

import {
    PatternsList,
    SequencerPattern
} from "patterns.slint";

SequencerPattern := Rectangle {
    callback clicked();
    property<int> number;
    property<bool> highlighted;
    property<bool> fill;
    background: fill ? #c0c0c0 : white;
    border_width: 1px;
    border_color: highlighted ? black : #a0a0a0;
    border_radius: width/8;
    Text {
        text: "P" + (number + 1);
        width: 100%;
        height: 100%;
        font_size: min(width, height) / 2.5;
        color: highlighted ? #505050 : #a0a0a0;
        horizontal_alignment: center;
        vertical_alignment: center;
    }
    TouchArea {
        width: 100%;
        height: 100%;
        clicked => { root.clicked(); }
    }
}

export SongPanel := VerticalBox {
    property<length> scroll_gutter_width <=> patterns_list.scroll_gutter_width;
    HorizontalLayout {
        spacing: 2px;

        for pattern[idx] in GlobalEngine.sequencer_song_patterns:
        SequencerPattern {
            number: pattern.number;
            highlighted: pattern.active;
        }
    }
    patterns_list := PatternsList {
        clicked(idx) => { GlobalEngine.append_song_pattern(idx); }
    }
    HorizontalBox {
        height: 25%;
        padding: 0;

        Button {
            text: "⌫";
            clicked => { GlobalEngine.remove_last_song_pattern(); }
        }
        Button {
            text: "Clear";
            clicked => { GlobalEngine.clear_song_patterns(); }
        }
    }
}
