// Copyright © 2021 Jocelyn Turcotte <turcotte.j@gmail.com>
// SPDX-License-Identifier: MIT

export component ToolbarButton inherits Rectangle {
    callback clicked();
    in property text <=> t.text;
    in property text_color <=> t.color;
    in property<bool> enabled: true;
    background: !ta.pressed && enabled ? white : #f4f4f4;
    border_width: 1px;
    border_color: enabled ? #a0a0a0 : transparent;
    border_radius: self.width/16;
    width: self.height * 2 / 3;
    t := Text {
        x: 0px;
        width: 100%;
        height: 100%;
        font_size: self.width / 2.5;
        horizontal_alignment: center;
        vertical_alignment: center;
    }
    ta := TouchArea {
        width: 100%;
        height: 100%;
        clicked => { root.clicked(); }
    }
}
