// Copyright © 2021 Jocelyn Turcotte <turcotte.j@gmail.com>
// SPDX-License-Identifier: MIT

export component ToolbarButton inherits Rectangle {
    callback clicked();
    in property text <=> t.text;
    in property text_color <=> t.color;
    in property<bool> enabled: true;
    background: !ta.pressed && enabled ? white : #f4f4f4;
    border_width: 1px;
    border_color: enabled ? #a0a0a0 : transparent;
    border_radius: self.width/16;
    width: self.height * 2 / 3;
    t := Text {
        x: 0px;
        width: 100%;
        height: 100%;
        font_size: self.width / 2;
        horizontal_alignment: center;
        vertical_alignment: center;
    }
    ta := TouchArea {
        width: 100%;
        height: 100%;
        clicked => { root.clicked(); }
    }
}

export component ScrollableSelection inherits TouchArea {
    callback scrolled(int);
    in property<int> cur_row;
    in property<int> viewport_rows;
    in-out property<int> total_rows;
    out property<int> scroll_row:
        max(floor(viewport_rows/2), 
            min(total_rows - floor(viewport_rows/2), cur_row))
        - floor(viewport_rows/2);
    in property<length> scrollbar_width;

    ta := TouchArea {
        width: scrollbar_width;
        x: 0px;
        property<int> v;
        moved => {
            if (self.pressed) {
                v = max(0, min(root.total_rows - 1, self.mouse_y / self.height * root.total_rows));
                if (v != root.cur_row) {
                    root.scrolled(v);
                }
            }
        }

        bar := Rectangle {
            x: 0px;
            y: root.cur_row * 1.0 / (root.total_rows - 1) * (parent.height - self.height);
            height: scrollbar_width * 4;
            width: 50%;
            background: grey;

        }
    }
    Rectangle {
        x: ta.width;
        width: parent.width - ta.width;
        @children
    }

}

